INSERT INTO USER_TABLE(user_id, status, name, role, email, password)  VALUES(1, 1, "Quitumba", "DEFAULT", "quitumba@email.com", "1234");

INSERT INTO PERMISSION_TABLE VALUES(1, "CREATE-DEFAULT-USER", "CREATE DEFAULT USER");
INSERT INTO PERMISSION_TABLE VALUES(2, "CREATE-ADMIN-USER", "CREATE ADMIN USER");
INSERT INTO PERMISSION_TABLE VALUES(3, "FIND-ALL-USER", "FIND ALL USER");
INSERT INTO PERMISSION_TABLE VALUES(4, "FIND-ONE-USER", "FIND ONE USER");

